# -*- coding: utf-8 -*-
"""lab 5 venkat ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L3OniFh63X0EkW7ltKLGiA5YYRNrImEx
"""

# Commented out IPython magic to ensure Python compatibility.
# %%html
# <div id="graph"></div>
# 
# <script src="https://cdn.jsdelivr.net/npm/d3@7/dist/d3.min.js"></script>
# 
# <script>
# 
# const width = 700;
# const height = 450;
# 
# const svg = d3.select("#graph")
#   .append("svg")
#   .attr("width", width)
#   .attr("height", height)
#   .style("border", "1px solid #ccc");
# 
# const nodes = [
#   { id: "Data Cleaning" },
#   { id: "EDA" },a
#   { id: "Feature Engineering" },
#   { id: "Model Training" },
#   { id: "Evaluation" },
#   { id: "Visualization" },
#   { id: "Deployment" }
# ];
# 
# 
# const links = [
#   { source: "Data Cleaning", target: "EDA" },
#   { source: "EDA", target: "Feature Engineering" },
#   { source: "Feature Engineering", target: "Model Training" },
#   { source: "Model Training", target: "Evaluation" },
#   { source: "Evaluation", target: "Visualization" },
#   { source: "Visualization", target: "Deployment" }
# ];
# 
# 
# const simulation = d3.forceSimulation(nodes)
#   .force(
#     "link",
#     d3.forceLink(links)
#       .id(d => d.id)
#       .distance(100)
#   )
#   .force("charge", d3.forceManyBody().strength(-300))
#   .force("center", d3.forceCenter(width / 2, height / 2));
# 
# 
# const link = svg.append("g")
#   .selectAll("line")
#   .data(links)
#   .enter()
#   .append("line")
#   .attr("stroke", "#999")
#   .attr("stroke-width", 2);
# 
# const node = svg.append("g")
#   .selectAll("circle")
#   .data(nodes)
#   .enter()
#   .append("circle")
#   .attr("r", 20)
#   .attr("fill", "#1f77b4")
#   .style("cursor", "grab");
# 
# const label = svg.append("g")
#   .selectAll("text")
#   .data(nodes)
#   .enter()
#   .append("text")
#   .text(d => d.id)
#   .attr("font-size", "12px")
#   .attr("text-anchor", "middle")
#   .attr("dy", 35);
# 
# 
# node
#   .on("mouseover", function() {
#     d3.select(this)
#       .transition()
#       .duration(200)
#       .attr("r", 28)
#       .attr("fill", "orange");
#   })
#   .on("mouseout", function() {
#     d3.select(this)
#       .transition()
#       .duration(200)
#       .attr("r", 20)
#       .attr("fill", "#1f77b4");
#   });
# 
# 
# node.call(
#   d3.drag()
#     .on("start", dragstarted)
#     .on("drag", dragged)
#     .on("end", dragended)
# );
# 
# function dragstarted(event, d) {
#   if (!event.active) simulation.alphaTarget(0.3).restart();
# 
#   d.fx = d.x;
#   d.fy = d.y;
# }
# 
# function dragged(event, d) {
#   d.fx = event.x;
#   d.fy = event.y;
# }
# 
# function dragended(event, d) {
#   if (!event.active) simulation.alphaTarget(0);
# 
#   d.fx = null;
#   d.fy = null;
# }
# 
# 
# simulation.on("tick", () => {
# 
#   link
#     .attr("x1", d => d.source.x)
#     .attr("y1", d => d.source.y)
#     .attr("x2", d => d.target.x)
#     .attr("y2", d => d.target.y);
# 
#   node
#     .attr("cx", d => d.x)
#     .attr("cy", d => d.y);
# 
#   label
#     .attr("x", d => d.x)
#     .attr("y", d => d.y);
# 
# });
# 
# </script>
#

# Commented out IPython magic to ensure Python compatibility.
# %%html
# 
# <div id="graph"></div>
# 
# <script src="https://cdn.jsdelivr.net/npm/d3@7/dist/d3.min.js"></script>
# <script src="https://cdn.jsdelivr.net/npm/d3-sankey@0.12.3/dist/d3-sankey.min.js"></script>
# 
# <script>
# 
# const width = 900;
# const height = 500;
# 
# const svg = d3.select("#graph")
#   .append("svg")
#   .attr("width", width)
#   .attr("height", height)
#   .style("border", "1px solid #ccc");
# 
# 
# 
# const nodes = [
#   { id: "Raw Data" },
#   { id: "Data Cleaning" },
#   { id: "Data Validation" },
#   { id: "EDA" },
#   { id: "Feature Engineering" },
#   { id: "Model Training" },
#   { id: "Evaluation" },
#   { id: "Visualization" },
#   { id: "Deployment" }
# ];
# 
# 
# const links = [
# 
#   { source: "Raw Data", target: "Data Cleaning", value: 50 },
#   { source: "Raw Data", target: "Data Validation", value: 30 },
# 
#   { source: "Data Cleaning", target: "EDA", value: 35 },
#   { source: "Data Cleaning", target: "Feature Engineering", value: 15 },
# 
#   { source: "Data Validation", target: "EDA", value: 20 },
#   { source: "Data Validation", target: "Feature Engineering", value: 10 },
# 
#   { source: "EDA", target: "Model Training", value: 30 },
#   { source: "EDA", target: "Visualization", value: 20 },
# 
#   { source: "Feature Engineering", target: "Model Training", value: 25 },
#   { source: "Feature Engineering", target: "Visualization", value: 10 },
# 
#   { source: "Model Training", target: "Evaluation", value: 45 },
# 
#   { source: "Evaluation", target: "Deployment", value: 40 },
#   { source: "Evaluation", target: "Visualization", value: 5 }
# 
# ];
# 
# 
# const sankey = d3.sankey()
#   .nodeId(d => d.id)
#   .nodeWidth(25)
#   .nodePadding(20)
#   .extent([
#     [20, 40],
#     [width - 20, height - 30]
#   ]);
# 
# 
# 
# 
# const graphData = sankey({
#   nodes: nodes.map(d => Object.assign({}, d)),
#   links: links.map(d => Object.assign({}, d))
# });
# 
# 
# 
# 
# const colors = [
#   "#1f77b4",
#   "#2ca02c",
#   "#ff7f0e",
#   "#9467bd",
#   "#17becf",
#   "#d62728",
#   "#e377c2",
#   "#8c564b",
#   "#7f7f7f"
# ];
# 
# 
# 
# 
# const link = svg.append("g")
#   .selectAll("path")
#   .data(graphData.links)
#   .enter()
#   .append("path")
#   .attr("d", d3.sankeyLinkHorizontal())
#   .attr("fill", "none")
#   .attr("stroke", "#999")
#   .attr("stroke-opacity", 0.4)
#   .attr("stroke-width", d => Math.max(1, d.width));
# 
# 
# 
# link.append("title")
#   .text(d =>
#     d.source.id + " → " +
#     d.target.id + " : " +
#     d.value
#   );
# 
# 
# 
# const node = svg.append("g")
#   .selectAll("g")
#   .data(graphData.nodes)
#   .enter()
#   .append("g");
# 
# 
# const nodeRect = node.append("rect")
#   .attr("x", d => d.x0)
#   .attr("y", d => d.y0)
#   .attr("width", d => d.x1 - d.x0)
#   .attr("height", d => d.y1 - d.y0)
#   .attr("fill", (d, i) => colors[i % colors.length])
#   .style("cursor", "pointer");
# 
# 
# 
# 
# nodeRect
#   .on("mouseover", function() {
# 
#     d3.select(this)
#       .transition()
#       .duration(200)
#       .attr("fill", "orange");
# 
#   })
# 
#   .on("mouseout", function(event, d) {
# 
#     const index = graphData.nodes.indexOf(d);
# 
#     d3.select(this)
#       .transition()
#       .duration(200)
#       .attr("fill", colors[index % colors.length]);
# 
#   });
# 
# 
# 
# nodeRect.append("title")
#   .text(d => d.id);
# 
# 
# 
# node.append("text")
#   .attr("x", d =>
#     d.x0 < width / 2
#       ? d.x1 + 7
#       : d.x0 - 7
#   )
#   .attr("y", d =>
#     (d.y0 + d.y1) / 2
#   )
#   .attr("dy", "0.35em")
#   .attr("text-anchor", d =>
#     d.x0 < width / 2
#       ? "start"
#       : "end"
#   )
#   .attr("font-size", "12px")
#   .attr("font-family", "Arial")
#   .text(d => d.id);
# 
# 
# 
# svg.append("text")
#   .attr("x", width / 2)
#   .attr("y", 25)
#   .attr("text-anchor", "middle")
#   .attr("font-size", "18px")
#   .attr("font-weight", "bold")
#   .text("Data Science Pipeline");
# 
# </script>

# Commented out IPython magic to ensure Python compatibility.
# %%html
# <div id="graph"></div>
# 
# <script src="https://cdn.jsdelivr.net/npm/d3@7/dist/d3.min.js"></script>
# 
# <script>
# 
# const width = 700;
# const height = 450;
# 
# 
# const svg = d3.select("#graph")
#   .append("svg")
#   .attr("width", width)
#   .attr("height", height)
#   .style("border", "1px solid #ccc");
# 
# 
# const data = {
#   name: "Data Science",
#   children: [
# 
#     {
#       name: "Data",
#       children: [
#         { name: "Data Cleaning", value: 30 },
#         { name: "Data Collection", value: 20 },
#         { name: "Data Preprocessing", value: 25 }
#       ]
#     },
# 
#     {
#       name: "Analysis",
#       children: [
#         { name: "EDA", value: 35 },
#         { name: "Statistics", value: 25 },
#         { name: "Feature Engineering", value: 30 }
#       ]
#     },
# 
#     {
#       name: "Modeling",
#       children: [
#         { name: "Model Training", value: 40 },
#         { name: "Evaluation", value: 30 },
#         { name: "Prediction", value: 25 }
#       ]
#     },
# 
#     {
#       name: "Deployment",
#       children: [
#         { name: "Visualization", value: 20 },
#         { name: "Dashboard", value: 25 },
#         { name: "Deployment", value: 30 }
#       ]
#     }
# 
#   ]
# };
# 
# 
# 
# const root = d3.hierarchy(data)
#   .sum(d => d.value);
# 
# d3.treemap()
#   .size([width, height])
#   .padding(3)
#   (root);
# 
# 
# 
# const colors = {
#   "Data": "#1f77b4",
#   "Analysis": "#2ca02c",
#   "Modeling": "#ff7f0e",
#   "Deployment": "#9467bd"
# };
# 
# 
# 
# const nodes = svg.selectAll("g")
#   .data(root.leaves())
#   .enter()
#   .append("g")
#   .attr(
#     "transform",
#     d => `translate(${d.x0},${d.y0})`
#   );
# 
# 
# nodes.append("rect")
#   .attr("width", d => d.x1 - d.x0)
#   .attr("height", d => d.y1 - d.y0)
#   .attr("fill", d => colors[d.parent.data.name])
#   .attr("stroke", "white")
#   .attr("stroke-width", 2)
#   .style("cursor", "pointer")
# 
#   // Hover effect
#   .on("mouseover", function(event, d) {
# 
#     d3.select(this)
#       .transition()
#       .duration(200)
#       .attr("opacity", 0.7);
# 
#     tooltip
#       .style("display", "block")
#       .html(
#         `<b>${d.data.name}</b><br>
#          Category: ${d.parent.data.name}<br>
#          Value: ${d.value}`
#       );
# 
#   })
# 
#   .on("mousemove", function(event) {
# 
#     tooltip
#       .style("left", (event.pageX + 10) + "px")
#       .style("top", (event.pageY + 10) + "px");
# 
#   })
# 
#   .on("mouseout", function() {
# 
#     d3.select(this)
#       .transition()
#       .duration(200)
#       .attr("opacity", 1);
# 
#     tooltip
#       .style("display", "none");
# 
#   });
# 
# 
# 
# nodes.append("text")
#   .attr("x", 5)
#   .attr("y", 18)
#   .attr("fill", "white")
#   .attr("font-size", "12px")
#   .attr("font-weight", "bold")
#   .text(d => d.data.name);
# 
# 
# 
# const tooltip = d3.select("#graph")
#   .append("div")
#   .style("position", "absolute")
#   .style("display", "none")
#   .style("background", "black")
#   .style("color", "white")
#   .style("padding", "8px")
#   .style("border-radius", "5px")
#   .style("font-size", "12px")
#   .style("pointer-events", "none");
# 
# 
# </script>

